# general config
graceTimeOut = 10
logLevel = "WARNING"

# entrypoints
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

# admin for debugging
[web]
address = ":8080"

# file config
[file]
filename = "/etc/traefik/rules.toml"
watch = true
